### ISSUE TITLE
Images other than classic dataset image gives (out of memory error)

### ISSUE THREAD

**Issue by subrakanthsutar** [YadiraF/PRNet#2]
Hi,

came across the out of memory Error when trying to input other images(other than classic dataset images). Is the image size anyway related to the error?

thank you.

![issue](https://user-images.githubusercontent.com/20366266/37824629-421fa712-2eb3-11e8-875e-01e8687effc9.png)

**Comment by YadiraF** [comment]
Yes, it is because of the image size.

Dlib is used for detecting face if you don't provide the bounding box information,  it occurs error if the image size is large(about >1000).

There are two ways you can solve the problem:
1. scale your image into a smaller size.
2. provide the bounding box information yourself with other detectors (highly recommended if convenience, since dlib is not so accurate)

Thanks for your reporting, I will add the check codes in case of further errors. : )
