### ISSUE TITLE
Texture Problem

### ISSUE THREAD

**Issue by BouOus** [YadiraF/PRNet#3]
Why don't I find good results in terms of texture?

![saved](https://user-images.githubusercontent.com/28622299/37834341-cabbc106-2ead-11e8-9edb-1485e4b566ae.jpg)

I changed the code to set opencv to True (for texture extraction) but nothing changed

Is this due to meshlab?
i have joined an output example

[0.zip](https://github.com/YadiraF/PRNet/files/1841838/0.zip)

Thank you

**Comment by YadiraF** [comment]
Yes, meshlab renders the mesh by default. 
You can close the light by `Render->Lighting->Light off` (see the screenshot) to view the original color.
![meshlab](https://user-images.githubusercontent.com/17000803/37837247-b6bdfd08-2eef-11e8-9145-9e21aecc14d2.png)

**Comment by BouafifOussema** [comment]
Thank you very much, i have solved the problem ;)
Another question please, is there a way to retrieve the code used for training?

**Comment by YadiraF** [comment]
If you mean the code for training the regression network, you can offer your email address then I can send you the code. It's very easy since I provide the network code for testing.
However, most of my work are preparing the training data, if you also need the code for generating the UV position map, there are some problems. One problem is that my code for generating training pairs is chaotic now, and some are written in C++ and compiled to python lib, I am not sure whether it can work at other machines. The other is that I have modified many other 3D data(BFM, expression, UV coordinates,etc) into my own version for better usage and I am afraid I have no permission to make it public.  So sorry for that.

**Comment by BouafifOussema** [comment]
Thank you very much, I sent you an email
